name: CI
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'
      - name: Fetch current ref
        if: "startsWith(github.ref, 'refs/tags/')"
        run: |
          git fetch --depth=1 origin +"$GITHUB_REF:$GITHUB_REF"
      - name: Install deps
        run: |
          pip install wheel
          pip install utz==0.1.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: "Docker: build, tag, and push"
        run: |
          docker/build.sh --push -t ${{ secrets.DOCKERHUB_TOKEN }} -u ${{ secrets.DOCKERHUB_USER }}
